baseURL = "/" # Đặt base URL là '/' để đảm bảo đường dẫn tài nguyên luôn bắt đầu từ thư thư mục gốc
languageCode = "vi"
title = "Blog Code Cơ Bản của Nguyễn Minh Vũ"
theme = "tella"


# =========================================================
# === CẤU HÌNH MENU CHÍNH =================================
# =========================================================
[[menu.main]]
  name = "Bài Code Cơ Bản"
  url = "/code/" # Tương ứng với thư mục content/code
  weight = 10

[[menu.main]]
  name = "Dự Án"
  url = "/projects/" # Tương ứng với thư mục content/projects
  weight = 20

[[menu.main]]
  name = "Về Tôi & CV"
  url = "/about/" # Tương ứng với thư mục content/about
  weight = 30


# =========================================================
# === THAM SỐ CHUNG (PARAMS) & CẤU HÌNH TRANG CHỦ ===========
# =========================================================
[params]
  # DÒNG CẤU HÌNH NÀY SẼ KÍCH HOẠT BANNER VÀ SERVICE BOXES
  homepage_section = ["hero", "services", "blog"]

# --- Cấu hình cho Banner lớn (Hero Section) ---
[params.hero]
  title = "BLOG CODE CƠ BẢN CỦA NGUYỄN MINH VŨ"
  subtitle = "Chia sẻ kiến thức lập trình cơ bản và các dự án cá nhân."
  
  # ⚠️ ĐIỀU CHỈNH ĐỂ TRỎ ĐẾN THƯ MỤC ASSETS MỚI:
  [[params.hero.slide]]
    # Đường dẫn trỏ đến file trong thư mục assets
    background_image = "assets/img/slide/minhvu-banner-1.jpg" 
    cta_text = "Xem Bài Code Đầu Tiên"
    cta_link = "/code/bai-code-dau-tien"
    
  [[params.hero.slide]]
    # Đường dẫn trỏ đến file trong thư mục assets
    background_image = "assets/img/slide/minhvu-banner-2.jpg"
    cta_text = "Xem Dự Án"
    cta_link = "/projects"


# --- Cấu hình cho Service Boxes (Simple, Fast, GitHub) ---
[[params.services]]
  icon = "fa-solid fa-code" # Biểu tượng code
  title = "Code Cơ Bản"
  description = "Tập trung vào kiến thức nền tảng HTML/CSS, Python, và Git."

[[params.services]]
  icon = "fa-solid fa-chalkboard" # Biểu tượng giảng dạy
  title = "Học Tập Hiệu Quả"
  description = "Các bài viết ngắn gọn, súc tích, dễ hiểu, giúp bạn học nhanh."

[[params.services]]
  icon = "fa-brands fa-github" # Biểu tượng GitHub
  title = "Dự Án Thực Tế"
  description = "Xem các dự án và mã nguồn trực tiếp trên GitHub của tôi."
  # Link_url = "https://github.com/yourusername" # Hãy thay bằng link GitHub của bạn


# --- Cấu hình cho phần Blog Listing (Hiển thị các bài viết) ---
[params.blog]
  title = "Các Bài Viết Code Mới Nhất"

# =========================================================
# === CẤU HÌNH KHÁC =======================================
# =========================================================

# Cấu hình Markdown Renderer (Goldmark)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Cho phép HTML thô trong Markdown
      unsafe = true

# Cấu hình Imaging (để Hugo xử lý tài nguyên trong assets)
[imaging]
  resampleFilter = "Box"
  quality = 75
  anchor = "smart"
  
  [imaging.exif]
    includeFields = ".*"
    timeZone = "Local"
